#ifndef TILETYPE_HPP
#define TILETYPE_HPP

#include <array>

#include "SFML\Graphics.hpp"


enum class TileType
{
	VOID,
	GRASS,
	DIRT,
	WATER,
	EMPTY1,
	EMPTY2,

	GRASS_DIRT_TRANSITION_1,
	GRASS_DIRT_TRANSITION_2,
	GRASS_DIRT_TRANSITION_3,
	GRASS_DIRT_TRANSITION_4,
	GRASS_DIRT_TRANSITION_5,
	GRASS_DIRT_TRANSITION_6,
	GRASS_DIRT_TRANSITION_7,
	GRASS_DIRT_TRANSITION_8,
	GRASS_DIRT_TRANSITION_9,
	GRASS_DIRT_TRANSITION_10,
	GRASS_DIRT_TRANSITION_11,
	GRASS_DIRT_TRANSITION_12,
	GRASS_DIRT_TRANSITION_13,
	GRASS_DIRT_TRANSITION_14,
	GRASS_DIRT_TRANSITION_15,
	GRASS_DIRT_TRANSITION_16,
	GRASS_DIRT_TRANSITION_17,
	GRASS_DIRT_TRANSITION_18,
	GRASS_DIRT_TRANSITION_19,
	GRASS_DIRT_TRANSITION_20,
	GRASS_DIRT_TRANSITION_21,
	GRASS_DIRT_TRANSITION_22,
	GRASS_DIRT_TRANSITION_23,
	GRASS_DIRT_TRANSITION_24,
	GRASS_DIRT_TRANSITION_25,
	GRASS_DIRT_TRANSITION_26,
	GRASS_DIRT_TRANSITION_27,
	GRASS_DIRT_TRANSITION_28,

	WATER_GRASS_TRANSITION_1,
	WATER_GRASS_TRANSITION_2,
	WATER_GRASS_TRANSITION_3,
	WATER_GRASS_TRANSITION_4,
	WATER_GRASS_TRANSITION_5,
	WATER_GRASS_TRANSITION_6,
	WATER_GRASS_TRANSITION_7,
	WATER_GRASS_TRANSITION_8,
	WATER_GRASS_TRANSITION_9,
	WATER_GRASS_TRANSITION_10,
	WATER_GRASS_TRANSITION_11,
	WATER_GRASS_TRANSITION_12,
	WATER_GRASS_TRANSITION_13,
	WATER_GRASS_TRANSITION_14,
	WATER_GRASS_TRANSITION_15,
	WATER_GRASS_TRANSITION_16,
	WATER_GRASS_TRANSITION_17,
	WATER_GRASS_TRANSITION_18,

	BRICKED_1,
	BRICKED_2,
	BRICKED_3,
	BRICKED_4,
	BRICKED_5,
	BRICKED_6,
	BRICKED_7,
	BRICKED_8,
	BRICKED_9,


	NUM_OF_TILE_TYPES
};

enum class TileTypeCategory
{
	NONE,

	GRASS,
	DIRT,
	WATER,
	BRICKED,


	NUM_OF_CATEGORIES
};

class TileTypeProperties
{
private:
	static const std::array<sf::Vector2u, static_cast<unsigned int>(TileType::NUM_OF_TILE_TYPES)> mPositionsArray;
	static const std::array<TileTypeCategory, static_cast<unsigned int>(TileType::NUM_OF_TILE_TYPES)> mCategoryArray;

public:
	static sf::Vector2u getPosition(TileType tileType);
	static TileTypeCategory getCategory(TileType tileType);

};



#endif //TILETYPE_HPP

